apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aeolus-report-monitor
  namespace: aeolus
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: aeolus-cron
        spec:
          # 非必须
          #nodeSelector:
          #  node: sub
          #hostNetwork: false
          #dnsPolicy: Default
          containers:
          - name: aeolus-report-monitor
            image: aeolus.vpc.com/library/xuyi_test:1.0.0.263
            imagePullPolicy: IfNotPresent
            env:
              - name: APP_DEPLOY_ENV
                value: AEOLUS_TOB_ENV
              - name: DEPLOY_ENV
                value: PROD
              - name: DB_USER
                value: aeolus_db_w
              - name: DB_PASSWD
                value: ccukDFrkmnQfoy7KPQHKZYC7XzbJsHuS
              # -------邮件服务---------
              # 邮件正文中产品标识
              - name: PRODUCT_NAME
                value: DataWind
              # 部署服务地址
              # TODO: 部署前必须修改
              - name: PRODUCT_DOMAIN
                value: http://218.205.220.74:32000
              - name: PRODUCT_URL_PREFIX
                value: bi
              - name: SMTP_EMAIL_USERNAME
                value: datawind@yeah.net
              - name: SMTP_EMAIL_PASSWORD
                value: PKACIKCPFPDVPNUB
              - name: SMTP_EMAIL_SERVER
                value: 123.58.177.131
              - name: SMTP_EMAIL_PORT
                value: "465"
              # 发件人名称
              - name: SMTP_EMAIL_SIGNATURE
                value: DataWind
            command: ["/bin/sh"]
            args: ["-c", "cd /opt/tiger/toutiao/app/data/aeolus; python -m aeolus.scripts.so_caller.check_monitor"]
            volumeMounts:
            - name: sock
              mountPath: /opt/tmp/sock
            - name: hadoop
              mountPath: /opt/tiger/yarn_deploy/hadoop
            - name: jdk8
              mountPath: /opt/tiger/jdk/jdk1.8.0_181
          volumes:
          - name: sock
            hostPath:
              path: /opt/tmp/sock
          - name: hadoop
            hostPath:
              path: /opt/tiger/yarn_deploy/hadoop
          - name: jdk8
            hostPath:
              path: /opt/tiger/jdk/jdk1.8.0_181
          restartPolicy: OnFailure
