# 定义模块命名空间, 每个服务模块对应一个命名空间
apiVersion: v1
kind: Namespace
metadata:
  name: vqs
---
# 命名空间内实例资源定义
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-vqs
  namespace: vqs
spec:
  limits:
  - type: Pod
    min:
      cpu: 50m
      memory: 5Mi
    max:
      cpu: 1
      memory: 2Gi
  - type: Container
    defaultRequest:       # 默认的内存/cpu请求
      cpu: 500m
      memory: 1Gi
    default:              # 默认的内存/cpu限制
      cpu: 500m
      memory: 1Gi
---
# 命名空间内总体资源限制
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-vqs
  namespace: vqs
spec:
  hard:                    # 每个容器必须有内存请求和限制，以及 CPU 请求和限制
    requests.cpu: 10       # 所有容器的 CPU 请求总和不能超过2 cpu
    requests.memory: 20Gi  # 所有容器的内存请求总和不能超过2 GiB
    limits.cpu: 20         # 所有容器的 CPU 限制总和不能超过4 cpu
    limits.memory: 50Gi   # 所有容器的内存限制总和不能超过10 GiB
---
# Deployment部署方式定义Pod及Container具体参数
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: vpc-vqs-be
  namespace: vqs
spec:
  selector:
    matchLabels:
      app: vpc-vqs-be
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: vpc-vqs-be
    spec:
      containers:
      - name: vpc-vqs-be
        #image: hub.byted.org/test/vqs_saas:44f8c770f74e9df6acb51cec0831f565
        image: aeolus.vpc.com/library/xuyi_vqs_test:1.0.1
        imagePullPolicy: IfNotPresent
        env:
          - name: HADOOP_HOME
            value: /opt/tiger/yarn_deploy/hadoop
          - name: DB_USER
            value: aeolus_db_w
          - name: DB_PASSWD
            value: ccukDFrkmnQfoy7KPQHKZYC7XzbJsHuS
          - name: AEOLUS_API_PSM
            value: data.aeolus.api.xuyi
        command: ["/bin/sh"]
        args: ["-c", "/opt/tiger/toutiao/app/data/vqs/run/tob_prod_run.sh"]
        ports:
        - containerPort: 12355
        # 可选, 存活探针, 确定何时重启容器
        livenessProbe:
          httpGet:
            path: /vqs/api/v2/misc/healthz
            port: 12355
            httpHeaders:
            - name: Content-type
              value: application/json
            - name: accept
              value: application/json, text/plain, */*
          initialDelaySeconds: 5   # 容器启动后第一次执行探测需要等待多少秒
          periodSeconds: 60         # 执行探测的频率. 默认是10秒, 最小1秒
        # 可选, 就绪探针, 确定容器是否已经就绪可以接受流量
        readinessProbe:
          httpGet:
            path: /vqs/api/v2/misc/healthz
            port: 12355
            httpHeaders:
            - name: Content-type
              value: application/json
            - name: accept
              value: application/json, text/plain, */*
          initialDelaySeconds: 5
          periodSeconds: 60
        volumeMounts:
        - name: sock
          mountPath: /opt/tmp/sock
        - name: hadoop
          mountPath: /opt/tiger/yarn_deploy/hadoop
        - name: hive
          mountPath: /opt/tiger/hive_deploy
        - name: jdk8
          mountPath: /opt/tiger/jdk/jdk1.8.0_181
      volumes:
      - name: sock
        hostPath:
          path: /opt/tmp/sock
      - name: hadoop
        hostPath:
          path: /opt/tiger/yarn_deploy/hadoop
      - name: hive
        hostPath:
          path: /opt/tiger/hive_deploy
      - name: jdk8
        hostPath:
          path: /opt/tiger/jdk/jdk1.8.0_181

---
# Service资源定义
apiVersion: v1
kind: Service
metadata:
  name: vpc-vqs-be
  namespace: vqs
  annotations:
    consul.register/enabled: "true"
    consul.register/service.name: "data.vqs.api"  # service.name 集群内服务自动发现注册至consul用
    consul.register/service.health.ttl: "8640000s"
spec:
  # 定义外部访问端口到服务端口映射
  type: NodePort
  ports:
    - port: 12355
      nodePort: 31100
      targetPort: 12355
  selector:
    app: vpc-vqs-be
